export type {
  Dimension,
  DimensionSeed,
  DimensionSource,
  Relationship,
  RelationshipOrigin,
  RelationshipMemory,
  LongTermMemory,
  RelationshipEvent,
  Pattern,
  RelationshipSeed,
  RelationshipTemplate,
  EvolutionRule,
  MemoryAdapter,
  RelationshipContext,
  RelationshipQueryResult,
  PathResult,
  ClusterResult,
} from './types.js';
